version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://flask_user:flask_password@db:5432/flask_db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: flask_db
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: flask_password
